### ISSUE TITLE
graphql dev dep?

### ISSUE THREAD

**Issue by IsaacSomething** [JsssCode/SmallAwesomeShop#1]
Hey cool fork. Very helpful.

You should update this version with the updated environment files. 

Just wondering, why is `graphql-js-client`  is a dev dependency, should it not be a code dependency?

**Comment by JsssCode** [comment]
Thanks for your attention to this repo and your remarks.  graphql-js-client was added to 'project dependencies', readme.txt was updated as well. 
Looking forward to further improvement suggestions!
