### ISSUE TITLE
get products in collection

### ISSUE THREAD

**Issue by danielfigueroaj** [JsssCode/SmallAwesomeShop#2]
Do you have a method to fetch all products in collection?

**Comment by danielfigueroaj** [comment]
I created this method based on the getProductById method that already exists, maybe you could add it to your service:

getProductsInCollection(_id):Promise<Product> {
    let client = this.client;
    let query = client.query((root) => {
      root.add('node', {args: {id: _id}, alias: 'collection'}, (node) => {
        node.addInlineFragmentOn('Collection', (collection) => {
          collection.addConnection('products', {args: {first: 250}}, (products) => {
            products.add('id');
            products.add('title');
            products.addConnection('images', {args: {first: 250}}, (images) => {
              images.add('src');
              images.add('id');
              images.add('altText');
            })
          })
        })
      })
    });

    return client.send(query).then(({ model, data }) => {
      return client.fetchAllPages(model.collection.products, {pageSize: 250})
    });
  }

Calling in component:
this.shopifyService.getProductsInCollection("someCollectionID").then((products) => {
      console.log("collection's products: " + JSON.stringify(products))
  
    });

**Comment by JsssCode** [comment]
Thanks @danielfigueroaj . I have added getProductsInCollection function to shopify.service [https://github.com/JsssCode/SmallAwesomeShop/commit/e308ae169bfd439f36c7449e79d1567e7e7971e8](commit link). Maybe later I will create a component.

**Comment by danielfigueroaj** [comment]
You're welcome, thank you!

**Comment by danielfigueroaj** [comment]
I forgot to mention, that the collectionId param must be the storefront ID, for example: Z2ldisddckjsislmeS98DMowi8jsNaosi89djMD5M9JKsksl not the ID in shopify admin like this: 93847562093
